### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by demist** [topogar/tp#1]
1. Нет схемы архитектуры
2. Описание же - нечеткое. Нужны указания конкретных названий классов
3. Писать весь код в одном файле - плохое решение
4. Константные строки должны быть вынесены в отдельный файл ресурсов, в крайнем случае - дефайны или статики
5. То же самое относится и к константным числам
6. Нарушения codestyle (разные куски выглядят по-разному, противоречит оформление)

**Comment by topogar** [comment]
Переделал

**Comment by demist** [comment]
засчитано
